- name: GitHubTrend
  urls:
    - https://api.github.com/search/repositories?q=created:>%s&sort=stars&order=desc&per_page=10
    - https://api.github.com/search/repositories?q=language:Go+created:>%s&sort=stars&order=desc&per_page=10
    - https://api.github.com/search/repositories?q=language:Java+created:>%s&sort=stars&order=desc&per_page=10
    - https://api.github.com/search/repositories?q=language:swift+created:>%s&sort=stars&order=desc&per_page=10