apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ncol
  labels:
    app: ncol
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ncol
    spec:
      containers:
      - name: ncol-app
        image: asia.gcr.io/carbon-folder-159903/ncol:0.1
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 1323